[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
lib_deps =
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    madhephaestus/ESP32Servo
    adafruit/DHT sensor library